import type { University } from "./types";

// Fallback Group of Eight + 4 strategic non-G8 unis used while Gideon's
// full 30-uni dataset is in flight. Tuition + IELTS figures are 2025 published
// rates from each university's international student handbook.

export const seedUniversities: University[] = [
  {
    id: "unsw",
    name: "University of New South Wales",
    short_name: "UNSW",
    city: "Sydney",
    state: "NSW",
    qs_ranking_2025: 19,
    is_group_of_eight: true,
    cricos_code: "00098G",
    website: "https://www.unsw.edu.au",
    logo_letter: "U",
    hero_color: "#FDB515",
    courses: [
      { course_name: "Bachelor of Computer Science", level: "undergraduate", field: "IT", duration_months: 36, annual_fee_aud: 53760, ielts_min: 6.5, gpa_min: 7.0, pr_eligible: true },
      { course_name: "Master of Information Technology", level: "postgraduate", field: "IT", duration_months: 24, annual_fee_aud: 56160, ielts_min: 6.5, gpa_min: 6.5, pr_eligible: true },
      { course_name: "Bachelor of Engineering (Honours)", level: "undergraduate", field: "Engineering", duration_months: 48, annual_fee_aud: 56880, ielts_min: 6.5, gpa_min: 7.5, pr_eligible: true },
      { course_name: "Master of Commerce", level: "postgraduate", field: "Business", duration_months: 24, annual_fee_aud: 54720, ielts_min: 7.0, gpa_min: 6.5, pr_eligible: false },
    ],
  },
  {
    id: "usyd",
    name: "The University of Sydney",
    short_name: "USyd",
    city: "Sydney",
    state: "NSW",
    qs_ranking_2025: 18,
    is_group_of_eight: true,
    cricos_code: "00026A",
    website: "https://www.sydney.edu.au",
    logo_letter: "S",
    hero_color: "#E64626",
    courses: [
      { course_name: "Bachelor of Advanced Computing", level: "undergraduate", field: "IT", duration_months: 36, annual_fee_aud: 55500, ielts_min: 6.5, gpa_min: 7.0, pr_eligible: true },
      { course_name: "Master of Data Science", level: "postgraduate", field: "IT", duration_months: 18, annual_fee_aud: 58000, ielts_min: 6.5, gpa_min: 6.5, pr_eligible: true },
      { course_name: "Bachelor of Engineering Honours (Civil)", level: "undergraduate", field: "Engineering", duration_months: 48, annual_fee_aud: 56500, ielts_min: 6.5, gpa_min: 7.5, pr_eligible: true },
      { course_name: "Master of Public Health", level: "postgraduate", field: "Health", duration_months: 18, annual_fee_aud: 54000, ielts_min: 7.0, gpa_min: 6.5, pr_eligible: true },
    ],
  },
  {
    id: "unimelb",
    name: "The University of Melbourne",
    short_name: "Melbourne",
    city: "Melbourne",
    state: "VIC",
    qs_ranking_2025: 13,
    is_group_of_eight: true,
    cricos_code: "00116K",
    website: "https://www.unimelb.edu.au",
    logo_letter: "M",
    hero_color: "#094183",
    courses: [
      { course_name: "Bachelor of Science (Computing)", level: "undergraduate", field: "IT", duration_months: 36, annual_fee_aud: 51008, ielts_min: 6.5, gpa_min: 7.5, pr_eligible: true },
      { course_name: "Master of Information Technology", level: "postgraduate", field: "IT", duration_months: 24, annual_fee_aud: 56960, ielts_min: 6.5, gpa_min: 6.5, pr_eligible: true },
      { course_name: "Master of Engineering (Software)", level: "postgraduate", field: "Engineering", duration_months: 36, annual_fee_aud: 56544, ielts_min: 6.5, gpa_min: 7.0, pr_eligible: true },
      { course_name: "Master of Business Administration", level: "postgraduate", field: "Business", duration_months: 24, annual_fee_aud: 99840, ielts_min: 7.0, gpa_min: 7.0, pr_eligible: false },
    ],
  },
  {
    id: "monash",
    name: "Monash University",
    short_name: "Monash",
    city: "Melbourne",
    state: "VIC",
    qs_ranking_2025: 37,
    is_group_of_eight: true,
    cricos_code: "00008C",
    website: "https://www.monash.edu",
    logo_letter: "M",
    hero_color: "#006DAE",
    courses: [
      { course_name: "Bachelor of Computer Science (Advanced)", level: "undergraduate", field: "IT", duration_months: 48, annual_fee_aud: 50300, ielts_min: 6.5, gpa_min: 7.0, pr_eligible: true },
      { course_name: "Master of Data Science", level: "postgraduate", field: "IT", duration_months: 24, annual_fee_aud: 50500, ielts_min: 6.5, gpa_min: 6.0, pr_eligible: true },
      { course_name: "Bachelor of Nursing", level: "undergraduate", field: "Health", duration_months: 36, annual_fee_aud: 47800, ielts_min: 7.0, gpa_min: 6.5, pr_eligible: true },
      { course_name: "Bachelor of Business", level: "undergraduate", field: "Business", duration_months: 36, annual_fee_aud: 49500, ielts_min: 6.5, gpa_min: 6.0, pr_eligible: false },
    ],
  },
  {
    id: "uq",
    name: "The University of Queensland",
    short_name: "UQ",
    city: "Brisbane",
    state: "QLD",
    qs_ranking_2025: 40,
    is_group_of_eight: true,
    cricos_code: "00025B",
    website: "https://www.uq.edu.au",
    logo_letter: "Q",
    hero_color: "#51247A",
    courses: [
      { course_name: "Bachelor of Computer Science", level: "undergraduate", field: "IT", duration_months: 36, annual_fee_aud: 50880, ielts_min: 6.5, gpa_min: 6.5, pr_eligible: true },
      { course_name: "Master of Computer Science", level: "postgraduate", field: "IT", duration_months: 24, annual_fee_aud: 52320, ielts_min: 6.5, gpa_min: 6.0, pr_eligible: true },
      { course_name: "Bachelor of Engineering Honours", level: "undergraduate", field: "Engineering", duration_months: 48, annual_fee_aud: 51840, ielts_min: 6.5, gpa_min: 7.0, pr_eligible: true },
      { course_name: "Master of Pharmaceutical Industry Practice", level: "postgraduate", field: "Health", duration_months: 18, annual_fee_aud: 47520, ielts_min: 7.0, gpa_min: 6.5, pr_eligible: true },
    ],
  },
  {
    id: "anu",
    name: "Australian National University",
    short_name: "ANU",
    city: "Canberra",
    state: "ACT",
    qs_ranking_2025: 30,
    is_group_of_eight: true,
    cricos_code: "00120C",
    website: "https://www.anu.edu.au",
    logo_letter: "A",
    hero_color: "#9C168F",
    courses: [
      { course_name: "Bachelor of Advanced Computing (Honours)", level: "undergraduate", field: "IT", duration_months: 48, annual_fee_aud: 52410, ielts_min: 6.5, gpa_min: 7.5, pr_eligible: true },
      { course_name: "Master of Computing", level: "postgraduate", field: "IT", duration_months: 24, annual_fee_aud: 53310, ielts_min: 6.5, gpa_min: 6.5, pr_eligible: true },
      { course_name: "Master of Engineering", level: "postgraduate", field: "Engineering", duration_months: 24, annual_fee_aud: 54000, ielts_min: 6.5, gpa_min: 6.5, pr_eligible: true },
      { course_name: "Bachelor of Politics, Philosophy & Economics", level: "undergraduate", field: "Arts", duration_months: 36, annual_fee_aud: 49170, ielts_min: 6.5, gpa_min: 7.0, pr_eligible: false },
    ],
  },
  {
    id: "uwa",
    name: "The University of Western Australia",
    short_name: "UWA",
    city: "Perth",
    state: "WA",
    qs_ranking_2025: 77,
    is_group_of_eight: true,
    cricos_code: "00126G",
    website: "https://www.uwa.edu.au",
    logo_letter: "W",
    hero_color: "#27348B",
    courses: [
      { course_name: "Bachelor of Computer Science", level: "undergraduate", field: "IT", duration_months: 36, annual_fee_aud: 44400, ielts_min: 6.5, gpa_min: 6.5, pr_eligible: true },
      { course_name: "Master of IT", level: "postgraduate", field: "IT", duration_months: 24, annual_fee_aud: 45200, ielts_min: 6.5, gpa_min: 6.0, pr_eligible: true },
      { course_name: "Bachelor of Engineering Science", level: "undergraduate", field: "Engineering", duration_months: 36, annual_fee_aud: 46800, ielts_min: 6.5, gpa_min: 6.5, pr_eligible: true },
      { course_name: "Master of Business Analytics", level: "postgraduate", field: "Business", duration_months: 18, annual_fee_aud: 46900, ielts_min: 6.5, gpa_min: 6.0, pr_eligible: false },
    ],
  },
  {
    id: "adelaide",
    name: "The University of Adelaide",
    short_name: "Adelaide",
    city: "Adelaide",
    state: "SA",
    qs_ranking_2025: 82,
    is_group_of_eight: true,
    cricos_code: "00123M",
    website: "https://www.adelaide.edu.au",
    logo_letter: "A",
    hero_color: "#102030",
    regional: true,
    courses: [
      { course_name: "Bachelor of Computer Science", level: "undergraduate", field: "IT", duration_months: 36, annual_fee_aud: 47000, ielts_min: 6.0, gpa_min: 6.0, pr_eligible: true },
      { course_name: "Master of Computing & Innovation", level: "postgraduate", field: "IT", duration_months: 18, annual_fee_aud: 48500, ielts_min: 6.5, gpa_min: 6.0, pr_eligible: true },
      { course_name: "Bachelor of Nursing", level: "undergraduate", field: "Health", duration_months: 36, annual_fee_aud: 44500, ielts_min: 7.0, gpa_min: 6.5, pr_eligible: true },
      { course_name: "Master of Wine Business", level: "postgraduate", field: "Business", duration_months: 18, annual_fee_aud: 44000, ielts_min: 6.5, gpa_min: 6.0, pr_eligible: false },
    ],
  },
  {
    id: "uts",
    name: "University of Technology Sydney",
    short_name: "UTS",
    city: "Sydney",
    state: "NSW",
    qs_ranking_2025: 88,
    is_group_of_eight: false,
    cricos_code: "00099F",
    website: "https://www.uts.edu.au",
    logo_letter: "T",
    hero_color: "#000000",
    courses: [
      { course_name: "Bachelor of Computing Science (Honours)", level: "undergraduate", field: "IT", duration_months: 48, annual_fee_aud: 47490, ielts_min: 6.5, gpa_min: 6.0, pr_eligible: true },
      { course_name: "Master of Information Technology", level: "postgraduate", field: "IT", duration_months: 18, annual_fee_aud: 48360, ielts_min: 6.5, gpa_min: 5.5, pr_eligible: true },
      { course_name: "Bachelor of Engineering (Honours)", level: "undergraduate", field: "Engineering", duration_months: 48, annual_fee_aud: 49560, ielts_min: 6.5, gpa_min: 6.0, pr_eligible: true },
      { course_name: "Master of Business Administration", level: "postgraduate", field: "Business", duration_months: 24, annual_fee_aud: 60500, ielts_min: 6.5, gpa_min: 6.5, pr_eligible: false },
    ],
  },
  {
    id: "wsu",
    name: "Western Sydney University",
    short_name: "WSU",
    city: "Penrith",
    state: "NSW",
    qs_ranking_2025: 376,
    is_group_of_eight: false,
    cricos_code: "00917K",
    website: "https://www.westernsydney.edu.au",
    logo_letter: "W",
    hero_color: "#E32726",
    regional: true,
    courses: [
      { course_name: "Bachelor of Information & Communications Technology", level: "undergraduate", field: "IT", duration_months: 36, annual_fee_aud: 32440, ielts_min: 6.0, gpa_min: 5.0, pr_eligible: true },
      { course_name: "Master of Information & Communications Technology", level: "postgraduate", field: "IT", duration_months: 24, annual_fee_aud: 34920, ielts_min: 6.5, gpa_min: 5.5, pr_eligible: true },
      { course_name: "Bachelor of Nursing", level: "undergraduate", field: "Health", duration_months: 36, annual_fee_aud: 35920, ielts_min: 7.0, gpa_min: 6.0, pr_eligible: true },
      { course_name: "Bachelor of Business", level: "undergraduate", field: "Business", duration_months: 36, annual_fee_aud: 32840, ielts_min: 6.0, gpa_min: 5.0, pr_eligible: false },
    ],
  },
  {
    id: "rmit",
    name: "RMIT University",
    short_name: "RMIT",
    city: "Melbourne",
    state: "VIC",
    qs_ranking_2025: 123,
    is_group_of_eight: false,
    cricos_code: "00122A",
    website: "https://www.rmit.edu.au",
    logo_letter: "R",
    hero_color: "#E61E2A",
    courses: [
      { course_name: "Bachelor of Information Technology", level: "undergraduate", field: "IT", duration_months: 36, annual_fee_aud: 41280, ielts_min: 6.5, gpa_min: 6.0, pr_eligible: true },
      { course_name: "Master of Data Science", level: "postgraduate", field: "IT", duration_months: 18, annual_fee_aud: 44160, ielts_min: 6.5, gpa_min: 5.5, pr_eligible: true },
      { course_name: "Bachelor of Engineering (Aerospace)", level: "undergraduate", field: "Engineering", duration_months: 48, annual_fee_aud: 44160, ielts_min: 6.5, gpa_min: 6.5, pr_eligible: true },
      { course_name: "Master of Architecture", level: "postgraduate", field: "Architecture", duration_months: 24, annual_fee_aud: 42240, ielts_min: 6.5, gpa_min: 6.0, pr_eligible: true },
    ],
  },
  {
    id: "wollongong",
    name: "University of Wollongong",
    short_name: "UOW",
    city: "Wollongong",
    state: "NSW",
    qs_ranking_2025: 167,
    is_group_of_eight: false,
    cricos_code: "00102E",
    website: "https://www.uow.edu.au",
    logo_letter: "W",
    hero_color: "#E61E2A",
    regional: true,
    courses: [
      { course_name: "Bachelor of Computer Science", level: "undergraduate", field: "IT", duration_months: 36, annual_fee_aud: 36720, ielts_min: 6.0, gpa_min: 5.5, pr_eligible: true },
      { course_name: "Master of Computer Science (AI)", level: "postgraduate", field: "IT", duration_months: 24, annual_fee_aud: 38760, ielts_min: 6.5, gpa_min: 5.5, pr_eligible: true },
      { course_name: "Bachelor of Engineering (Mechatronic)", level: "undergraduate", field: "Engineering", duration_months: 48, annual_fee_aud: 39240, ielts_min: 6.0, gpa_min: 6.0, pr_eligible: true },
      { course_name: "Bachelor of Nursing", level: "undergraduate", field: "Health", duration_months: 36, annual_fee_aud: 37920, ielts_min: 7.0, gpa_min: 6.0, pr_eligible: true },
    ],
  },
];
