import type { Course, University } from "./types";

const course = (
  course_name: string,
  level: Course["level"],
  field: Course["field"],
  duration_months: number,
  annual_fee_aud: number,
  ielts_min: number,
  gpa_min: number,
  industry_placement: boolean,
): Course => ({
  course_name,
  level,
  field,
  duration_months,
  annual_fee_aud,
  ielts_min,
  gpa_min,
  industry_placement,
});

// Source basis:
// - CRICOS official register dataset: https://data.gov.au/data/en/dataset/cricos
// - QS World University Rankings 2025: https://www.topuniversities.com/world-university-rankings/2025
// - Tuition / IELTS / GPA figures are compiled demo-friendly 2025 international-entry values
//   aligned to official university course pages and fee schedules, rounded for app use.
export const universities: University[] = [
  {
    id: "australian-national-university",
    name: "Australian National University",
    short_name: "ANU",
    city: "Canberra",
    state: "ACT",
    qs_ranking_2025: 30,
    is_group_of_eight: true,
    cricos_code: "00120C",
    website: "https://www.anu.edu.au",
    logo_letter: "A",
    hero_color: "#7A0019",
    courses: [
      course("Master of Computing", "postgraduate", "IT", 24, 50000, 6.5, 5, true),
      course("Bachelor of Engineering (Honours)", "undergraduate", "Engineering", 48, 56200, 6.5, 3, true),
      course("Master of Public Policy", "postgraduate", "Business", 24, 48200, 6.5, 5, false),
    ],
  },
  {
    id: "university-of-melbourne",
    name: "The University of Melbourne",
    short_name: "Melbourne",
    city: "Melbourne",
    state: "VIC",
    qs_ranking_2025: 13,
    is_group_of_eight: true,
    cricos_code: "00116K",
    website: "https://www.unimelb.edu.au",
    logo_letter: "M",
    hero_color: "#0C2340",
    courses: [
      course("Master of Information Technology", "postgraduate", "IT", 24, 56512, 6.5, 5, true),
      course("Master of Engineering", "postgraduate", "Engineering", 36, 58008, 6.5, 5, true),
      course("Master of Public Health", "postgraduate", "Health", 24, 52864, 6.5, 5, true),
    ],
  },
  {
    id: "university-of-sydney",
    name: "The University of Sydney",
    short_name: "Sydney",
    city: "Sydney",
    state: "NSW",
    qs_ranking_2025: 18,
    is_group_of_eight: true,
    cricos_code: "00026A",
    website: "https://www.sydney.edu.au",
    logo_letter: "S",
    hero_color: "#B0122B",
    courses: [
      course("Master of Computer Science", "postgraduate", "IT", 24, 54500, 6.5, 5, true),
      course("Bachelor of Engineering Honours", "undergraduate", "Engineering", 48, 58000, 6.5, 3, true),
      course("Master of Commerce", "postgraduate", "Business", 24, 56500, 7, 5, false),
    ],
  },
  {
    id: "unsw-sydney",
    name: "The University of New South Wales",
    short_name: "UNSW",
    city: "Sydney",
    state: "NSW",
    qs_ranking_2025: 19,
    is_group_of_eight: true,
    cricos_code: "00098G",
    website: "https://www.unsw.edu.au",
    logo_letter: "U",
    hero_color: "#FFCD00",
    courses: [
      course("Master of Information Technology", "postgraduate", "IT", 24, 59000, 6.5, 5, true),
      course("Master of Engineering Science", "postgraduate", "Engineering", 24, 55150, 6.5, 5, true),
      course("Master of Public Health", "postgraduate", "Health", 24, 46450, 6.5, 5, true),
    ],
  },
  {
    id: "monash-university",
    name: "Monash University",
    short_name: "Monash",
    city: "Melbourne",
    state: "VIC",
    qs_ranking_2025: 37,
    is_group_of_eight: true,
    cricos_code: "00008C",
    website: "https://www.monash.edu",
    logo_letter: "M",
    hero_color: "#005EB8",
    courses: [
      course("Master of Information Technology", "postgraduate", "IT", 24, 49300, 6.5, 5, true),
      course("Bachelor of Engineering (Honours)", "undergraduate", "Engineering", 48, 54400, 6.5, 3, true),
      course("Master of Nursing Practice", "postgraduate", "Health", 24, 42000, 7, 5, true),
    ],
  },
  {
    id: "university-of-queensland",
    name: "The University of Queensland",
    short_name: "UQ",
    city: "Brisbane",
    state: "QLD",
    qs_ranking_2025: 40,
    is_group_of_eight: true,
    cricos_code: "00025B",
    website: "https://www.uq.edu.au",
    logo_letter: "U",
    hero_color: "#51247A",
    courses: [
      course("Master of Data Science", "postgraduate", "IT", 24, 53360, 6.5, 5, true),
      course("Bachelor of Engineering (Honours)", "undergraduate", "Engineering", 48, 53560, 6.5, 3, true),
      course("Master of Public Health", "postgraduate", "Health", 24, 47080, 6.5, 5, true),
    ],
  },
  {
    id: "university-of-adelaide",
    name: "The University of Adelaide",
    short_name: "Adelaide",
    city: "Adelaide",
    state: "SA",
    qs_ranking_2025: 82,
    is_group_of_eight: true,
    cricos_code: "00123M",
    website: "https://www.adelaide.edu.au",
    logo_letter: "A",
    hero_color: "#0057B8",
    courses: [
      course("Master of Computer Science", "postgraduate", "IT", 24, 49500, 6.5, 4.5, true),
      course("Bachelor of Engineering (Honours)", "undergraduate", "Engineering", 48, 50800, 6, 3, true),
      course("Master of Public Health", "postgraduate", "Health", 24, 46800, 6.5, 4.5, true),
    ],
  },
  {
    id: "university-of-western-australia",
    name: "The University of Western Australia",
    short_name: "UWA",
    city: "Perth",
    state: "WA",
    qs_ranking_2025: 77,
    is_group_of_eight: true,
    cricos_code: "00126G",
    website: "https://www.uwa.edu.au",
    logo_letter: "U",
    hero_color: "#003366",
    courses: [
      course("Master of Information Technology", "postgraduate", "IT", 24, 47200, 6.5, 5, true),
      course("Master of Professional Engineering", "postgraduate", "Engineering", 24, 50600, 6.5, 5, true),
      course("Master of Business Analytics", "postgraduate", "Business", 24, 45600, 6.5, 5, false),
    ],
  },
  {
    id: "university-of-technology-sydney",
    name: "University of Technology Sydney",
    short_name: "UTS",
    city: "Sydney",
    state: "NSW",
    qs_ranking_2025: 88,
    is_group_of_eight: false,
    cricos_code: "00099F",
    website: "https://www.uts.edu.au",
    logo_letter: "U",
    hero_color: "#0F4C81",
    courses: [
      course("Master of Information Technology", "postgraduate", "IT", 24, 55008, 6.5, 4.5, true),
      course("Master of Engineering Management", "postgraduate", "Engineering", 18, 45936, 6.5, 4.5, true),
      course("Master of Business Analytics", "postgraduate", "Business", 24, 47808, 6.5, 4.5, false),
    ],
  },
  {
    id: "western-sydney-university",
    name: "Western Sydney University",
    short_name: "WSU",
    city: "Sydney",
    state: "NSW",
    qs_ranking_2025: 384,
    is_group_of_eight: false,
    cricos_code: "00917K",
    website: "https://www.westernsydney.edu.au",
    logo_letter: "W",
    hero_color: "#990033",
    courses: [
      course("Master of Information and Communications Technology", "postgraduate", "IT", 24, 34248, 6.5, 4.5, true),
      course("Bachelor of Nursing", "undergraduate", "Health", 36, 35280, 7, 3, true),
      course("Bachelor of Engineering (Honours)", "undergraduate", "Engineering", 48, 37608, 6.5, 3, true),
    ],
  },
  {
    id: "macquarie-university",
    name: "Macquarie University",
    short_name: "Macquarie",
    city: "Sydney",
    state: "NSW",
    qs_ranking_2025: 133,
    is_group_of_eight: false,
    cricos_code: "00002J",
    website: "https://www.mq.edu.au",
    logo_letter: "M",
    hero_color: "#C8102E",
    courses: [
      course("Master of Data Science", "postgraduate", "IT", 24, 44100, 6.5, 4.5, true),
      course("Bachelor of Engineering (Honours)", "undergraduate", "Engineering", 48, 44400, 6.5, 3, true),
      course("Master of Professional Accounting", "postgraduate", "Business", 24, 43000, 6.5, 4.5, false),
    ],
  },
  {
    id: "rmit-university",
    name: "RMIT University",
    short_name: "RMIT",
    city: "Melbourne",
    state: "VIC",
    qs_ranking_2025: 123,
    is_group_of_eight: false,
    cricos_code: "00122A",
    website: "https://www.rmit.edu.au",
    logo_letter: "R",
    hero_color: "#E60028",
    courses: [
      course("Master of Information Technology", "postgraduate", "IT", 24, 44320, 6.5, 4.5, true),
      course("Bachelor of Engineering (Honours)", "undergraduate", "Engineering", 48, 45120, 6.5, 3, true),
      course("Master of Supply Chain and Logistics Management", "postgraduate", "Business", 24, 40320, 6.5, 4.5, false),
    ],
  },
  {
    id: "deakin-university",
    name: "Deakin University",
    short_name: "Deakin",
    city: "Melbourne",
    state: "VIC",
    qs_ranking_2025: 197,
    is_group_of_eight: false,
    cricos_code: "00113B",
    website: "https://www.deakin.edu.au",
    logo_letter: "D",
    hero_color: "#0066B3",
    courses: [
      course("Master of Cyber Security", "postgraduate", "IT", 24, 41800, 6.5, 4.5, true),
      course("Bachelor of Nursing", "undergraduate", "Health", 36, 39200, 7, 3, true),
      course("Master of Social Work", "postgraduate", "Social Work", 24, 37000, 7, 4.5, true),
    ],
  },
  {
    id: "griffith-university",
    name: "Griffith University",
    short_name: "Griffith",
    city: "Gold Coast",
    state: "QLD",
    qs_ranking_2025: 255,
    is_group_of_eight: false,
    cricos_code: "00233E",
    website: "https://www.griffith.edu.au",
    logo_letter: "G",
    hero_color: "#D71920",
    courses: [
      course("Master of Information Technology", "postgraduate", "IT", 24, 39000, 6.5, 4.5, true),
      course("Bachelor of Engineering (Honours)", "undergraduate", "Engineering", 48, 39400, 6.5, 3, true),
      course("Bachelor of Nursing", "undergraduate", "Health", 36, 35600, 7, 3, true),
    ],
  },
  {
    id: "queensland-university-of-technology",
    name: "Queensland University of Technology",
    short_name: "QUT",
    city: "Brisbane",
    state: "QLD",
    qs_ranking_2025: 213,
    is_group_of_eight: false,
    cricos_code: "00213J",
    website: "https://www.qut.edu.au",
    logo_letter: "Q",
    hero_color: "#003C71",
    courses: [
      course("Master of Data Analytics", "postgraduate", "IT", 24, 36800, 6.5, 4.5, true),
      course("Bachelor of Engineering (Honours)", "undergraduate", "Engineering", 48, 40400, 6.5, 3, true),
      course("Master of Business", "postgraduate", "Business", 24, 38400, 6.5, 4.5, false),
    ],
  },
  {
    id: "la-trobe-university",
    name: "La Trobe University",
    short_name: "La Trobe",
    city: "Melbourne",
    state: "VIC",
    qs_ranking_2025: 217,
    is_group_of_eight: false,
    cricos_code: "00115M",
    website: "https://www.latrobe.edu.au",
    logo_letter: "L",
    hero_color: "#E87722",
    courses: [
      course("Master of Data Science", "postgraduate", "IT", 24, 41400, 6.5, 4.5, true),
      course("Bachelor of Nursing", "undergraduate", "Health", 36, 38200, 7, 3, true),
      course("Master of Social Work", "postgraduate", "Social Work", 24, 35600, 7, 4.5, true),
    ],
  },
  {
    id: "curtin-university",
    name: "Curtin University",
    short_name: "Curtin",
    city: "Perth",
    state: "WA",
    qs_ranking_2025: 174,
    is_group_of_eight: false,
    cricos_code: "00301J",
    website: "https://www.curtin.edu.au",
    logo_letter: "C",
    hero_color: "#B20000",
    courses: [
      course("Master of Predictive Analytics", "postgraduate", "IT", 24, 40300, 6.5, 4.5, true),
      course("Bachelor of Engineering (Honours)", "undergraduate", "Engineering", 48, 42100, 6.5, 3, true),
      course("Master of Public Health", "postgraduate", "Health", 24, 38900, 6.5, 4.5, true),
    ],
  },
  {
    id: "swinburne-university-of-technology",
    name: "Swinburne University of Technology",
    short_name: "Swinburne",
    city: "Melbourne",
    state: "VIC",
    qs_ranking_2025: 291,
    is_group_of_eight: false,
    cricos_code: "00111D",
    website: "https://www.swinburne.edu.au",
    logo_letter: "S",
    hero_color: "#E4002B",
    courses: [
      course("Master of Information Technology", "postgraduate", "IT", 24, 39160, 6.5, 4.5, true),
      course("Bachelor of Engineering (Honours)", "undergraduate", "Engineering", 48, 41400, 6.5, 3, true),
      course("Master of Construction and Infrastructure Management", "postgraduate", "Engineering", 24, 39560, 6.5, 4.5, true),
    ],
  },
  {
    id: "university-of-wollongong",
    name: "University of Wollongong",
    short_name: "UOW",
    city: "Wollongong",
    state: "NSW",
    qs_ranking_2025: 167,
    is_group_of_eight: false,
    cricos_code: "00102E",
    website: "https://www.uow.edu.au",
    logo_letter: "U",
    hero_color: "#006699",
    courses: [
      course("Master of Computer Science", "postgraduate", "IT", 24, 39456, 6.5, 4.5, true),
      course("Bachelor of Nursing", "undergraduate", "Health", 36, 34704, 7, 3, true),
      course("Master of Engineering", "postgraduate", "Engineering", 24, 41136, 6.5, 4.5, true),
    ],
  },
  {
    id: "university-of-newcastle",
    name: "The University of Newcastle",
    short_name: "Newcastle",
    city: "Newcastle",
    state: "NSW",
    qs_ranking_2025: 213,
    is_group_of_eight: false,
    cricos_code: "00109J",
    website: "https://www.newcastle.edu.au",
    logo_letter: "N",
    hero_color: "#003A65",
    courses: [
      course("Master of Information Technology", "postgraduate", "IT", 24, 38375, 6.5, 4.5, true),
      course("Bachelor of Engineering (Honours)", "undergraduate", "Engineering", 48, 39405, 6.5, 3, true),
      course("Master of Public Health", "postgraduate", "Health", 24, 36695, 6.5, 4.5, true),
    ],
  },
  {
    id: "university-of-canberra",
    name: "University of Canberra",
    short_name: "Canberra",
    city: "Canberra",
    state: "ACT",
    qs_ranking_2025: 403,
    is_group_of_eight: false,
    cricos_code: "00212K",
    website: "https://www.canberra.edu.au",
    logo_letter: "C",
    hero_color: "#005DAA",
    courses: [
      course("Master of Information Technology and Systems", "postgraduate", "IT", 24, 36200, 6.5, 4.5, true),
      course("Bachelor of Nursing", "undergraduate", "Health", 36, 34500, 7, 3, true),
      course("Master of Business Informatics", "postgraduate", "Business", 24, 35500, 6.5, 4.5, false),
    ],
  },
  {
    id: "charles-sturt-university",
    name: "Charles Sturt University",
    short_name: "CSU",
    city: "Wagga Wagga",
    state: "NSW",
    qs_ranking_2025: 851,
    is_group_of_eight: false,
    cricos_code: "00005F",
    website: "https://www.csu.edu.au",
    logo_letter: "C",
    hero_color: "#4B2E83",
    courses: [
      course("Master of Information Technology", "postgraduate", "IT", 24, 31200, 6, 4.5, true),
      course("Bachelor of Nursing", "undergraduate", "Health", 36, 33440, 7, 3, true),
      course("Master of Social Work (Professional Qualifying)", "postgraduate", "Social Work", 24, 30640, 7, 4.5, true),
    ],
  },
  {
    id: "bond-university",
    name: "Bond University",
    short_name: "Bond",
    city: "Gold Coast",
    state: "QLD",
    qs_ranking_2025: 567,
    is_group_of_eight: false,
    cricos_code: "00017B",
    website: "https://bond.edu.au",
    logo_letter: "B",
    hero_color: "#002B5C",
    courses: [
      course("Master of Data Analytics", "postgraduate", "IT", 16, 47520, 6.5, 4.5, true),
      course("Bachelor of Business", "undergraduate", "Business", 24, 48960, 6.5, 3, false),
      course("Master of Occupational Therapy", "postgraduate", "Health", 24, 51120, 7, 4.5, true),
    ],
  },
  {
    id: "university-of-notre-dame-australia",
    name: "The University of Notre Dame Australia",
    short_name: "Notre Dame",
    city: "Perth",
    state: "WA",
    qs_ranking_2025: 1201,
    is_group_of_eight: false,
    cricos_code: "01032F",
    website: "https://www.notredame.edu.au",
    logo_letter: "N",
    hero_color: "#003B71",
    courses: [
      course("Bachelor of Nursing", "undergraduate", "Health", 36, 36700, 7, 3, true),
      course("Master of Teaching", "postgraduate", "Education", 24, 33900, 7, 4.5, true),
      course("Bachelor of Physiotherapy", "undergraduate", "Health", 48, 40200, 7, 3, true),
    ],
  },
  {
    id: "victoria-university",
    name: "Victoria University",
    short_name: "VU",
    city: "Melbourne",
    state: "VIC",
    qs_ranking_2025: 587,
    is_group_of_eight: false,
    cricos_code: "00124K",
    website: "https://www.vu.edu.au",
    logo_letter: "V",
    hero_color: "#0055A4",
    courses: [
      course("Master of Applied Information Technology", "postgraduate", "IT", 24, 34400, 6.5, 4.5, true),
      course("Bachelor of Nursing", "undergraduate", "Health", 36, 33600, 7, 3, true),
      course("Master of Teaching (Primary Education)", "postgraduate", "Education", 24, 31100, 7, 4.5, true),
    ],
  },
  {
    id: "james-cook-university",
    name: "James Cook University",
    short_name: "JCU",
    city: "Townsville",
    state: "QLD",
    qs_ranking_2025: 445,
    is_group_of_eight: false,
    cricos_code: "00117J",
    website: "https://www.jcu.edu.au",
    logo_letter: "J",
    hero_color: "#00A3E0",
    courses: [
      course("Master of Information Technology", "postgraduate", "IT", 24, 36000, 6.5, 4.5, true),
      course("Bachelor of Nursing Science", "undergraduate", "Health", 36, 34280, 7, 3, true),
      course("Master of Engineering Management", "postgraduate", "Engineering", 24, 37200, 6.5, 4.5, true),
    ],
  },
  {
    id: "murdoch-university",
    name: "Murdoch University",
    short_name: "Murdoch",
    city: "Perth",
    state: "WA",
    qs_ranking_2025: 436,
    is_group_of_eight: false,
    cricos_code: "00125J",
    website: "https://www.murdoch.edu.au",
    logo_letter: "M",
    hero_color: "#C8102E",
    courses: [
      course("Master of Information Technology", "postgraduate", "IT", 24, 36960, 6.5, 4.5, true),
      course("Bachelor of Nursing", "undergraduate", "Health", 36, 36520, 7, 3, true),
      course("Master of Education", "postgraduate", "Education", 24, 32640, 6.5, 4.5, true),
    ],
  },
  {
    id: "flinders-university",
    name: "Flinders University",
    short_name: "Flinders",
    city: "Adelaide",
    state: "SA",
    qs_ranking_2025: 336,
    is_group_of_eight: false,
    cricos_code: "00114A",
    website: "https://www.flinders.edu.au",
    logo_letter: "F",
    hero_color: "#E87722",
    courses: [
      course("Master of Information Technology", "postgraduate", "IT", 24, 38800, 6.5, 4.5, true),
      course("Bachelor of Nursing (Graduate Entry)", "undergraduate", "Health", 24, 36400, 7, 3, true),
      course("Master of Social Work", "postgraduate", "Social Work", 24, 35200, 7, 4.5, true),
    ],
  },
  {
    id: "university-of-tasmania",
    name: "University of Tasmania",
    short_name: "UTAS",
    city: "Hobart",
    state: "TAS",
    qs_ranking_2025: 293,
    is_group_of_eight: false,
    cricos_code: "00586B",
    website: "https://www.utas.edu.au",
    logo_letter: "U",
    hero_color: "#C4002F",
    courses: [
      course("Master of Information Technology and Systems", "postgraduate", "IT", 24, 35835, 6.5, 4.5, true),
      course("Bachelor of Nursing", "undergraduate", "Health", 36, 35375, 7, 3, true),
      course("Master of Professional Engineering", "postgraduate", "Engineering", 24, 40250, 6.5, 4.5, true),
    ],
  },
  {
    id: "southern-cross-university",
    name: "Southern Cross University",
    short_name: "SCU",
    city: "Gold Coast",
    state: "QLD",
    qs_ranking_2025: 445,
    is_group_of_eight: false,
    cricos_code: "01241G",
    website: "https://www.scu.edu.au",
    logo_letter: "S",
    hero_color: "#004B87",
    courses: [
      course("Master of Information Technology", "postgraduate", "IT", 24, 30920, 6.5, 4.5, true),
      course("Bachelor of Nursing", "undergraduate", "Health", 36, 31200, 7, 3, true),
      course("Master of Teaching", "postgraduate", "Education", 24, 30240, 7, 4.5, true),
    ],
  },
  {
    id: "central-queensland-university",
    name: "Central Queensland University",
    short_name: "CQU",
    city: "Rockhampton",
    state: "QLD",
    qs_ranking_2025: 495,
    is_group_of_eight: false,
    cricos_code: "00219C",
    website: "https://www.cqu.edu.au",
    logo_letter: "C",
    hero_color: "#F05A28",
    courses: [
      course("Master of Information Systems", "postgraduate", "IT", 24, 33990, 6.5, 4.5, true),
      course("Bachelor of Nursing", "undergraduate", "Health", 36, 33960, 7, 3, true),
      course("Master of Engineering", "postgraduate", "Engineering", 24, 36720, 6.5, 4.5, true),
    ],
  },
  {
    id: "federation-university-australia",
    name: "Federation University Australia",
    short_name: "Federation",
    city: "Ballarat",
    state: "VIC",
    qs_ranking_2025: 1201,
    is_group_of_eight: false,
    cricos_code: "00103D",
    website: "https://federation.edu.au",
    logo_letter: "F",
    hero_color: "#C41230",
    courses: [
      course("Master of Technology (Enterprise Systems and Business Analytics)", "postgraduate", "IT", 24, 29400, 6, 4.5, true),
      course("Bachelor of Nursing", "undergraduate", "Health", 36, 30800, 7, 3, true),
      course("Master of Social Work (Qualifying)", "postgraduate", "Social Work", 24, 28600, 7, 4.5, true),
    ],
  },
  {
    id: "university-of-the-sunshine-coast",
    name: "University of the Sunshine Coast",
    short_name: "UniSC",
    city: "Sunshine Coast",
    state: "QLD",
    qs_ranking_2025: 1001,
    is_group_of_eight: false,
    cricos_code: "01595D",
    website: "https://www.usc.edu.au",
    logo_letter: "U",
    hero_color: "#00539B",
    courses: [
      course("Master of Information and Communications Technology", "postgraduate", "IT", 24, 32600, 6.5, 4.5, true),
      course("Bachelor of Nursing Science", "undergraduate", "Health", 36, 33400, 7, 3, true),
      course("Master of Teaching (Primary)", "postgraduate", "Education", 24, 28800, 7, 4.5, true),
    ],
  },
  {
    id: "edith-cowan-university",
    name: "Edith Cowan University",
    short_name: "ECU",
    city: "Perth",
    state: "WA",
    qs_ranking_2025: 403,
    is_group_of_eight: false,
    cricos_code: "00279B",
    website: "https://www.ecu.edu.au",
    logo_letter: "E",
    hero_color: "#005EB8",
    courses: [
      course("Master of Cyber Security", "postgraduate", "IT", 24, 37000, 6.5, 4.5, true),
      course("Bachelor of Nursing", "undergraduate", "Health", 36, 35950, 7, 3, true),
      course("Master of Engineering", "postgraduate", "Engineering", 24, 38650, 6.5, 4.5, true),
    ],
  },
  {
    id: "university-of-south-australia",
    name: "University of South Australia",
    short_name: "UniSA",
    city: "Adelaide",
    state: "SA",
    qs_ranking_2025: 340,
    is_group_of_eight: false,
    cricos_code: "00121B",
    website: "https://www.unisa.edu.au",
    logo_letter: "U",
    hero_color: "#00529B",
    courses: [
      course("Master of Information Technology", "postgraduate", "IT", 24, 37900, 6.5, 4.5, true),
      course("Bachelor of Construction Management (Honours)", "undergraduate", "Engineering", 48, 35700, 6, 3, true),
      course("Master of Social Work", "postgraduate", "Social Work", 24, 35200, 7, 4.5, true),
    ],
  },
  {
    id: "charles-darwin-university",
    name: "Charles Darwin University",
    short_name: "CDU",
    city: "Darwin",
    state: "NT",
    qs_ranking_2025: 621,
    is_group_of_eight: false,
    cricos_code: "00300K",
    website: "https://www.cdu.edu.au",
    logo_letter: "C",
    hero_color: "#B5121B",
    courses: [
      course("Master of Information Technology (Cyber Security)", "postgraduate", "IT", 24, 34032, 6.5, 4.5, true),
      course("Bachelor of Nursing", "undergraduate", "Health", 36, 33432, 7, 3, true),
      course("Master of Social Work (Qualifying)", "postgraduate", "Social Work", 24, 31464, 7, 4.5, true),
    ],
  },
  {
    id: "university-of-southern-queensland",
    name: "University of Southern Queensland",
    short_name: "UniSQ",
    city: "Toowoomba",
    state: "QLD",
    qs_ranking_2025: 410,
    is_group_of_eight: false,
    cricos_code: "00244B",
    website: "https://www.unisq.edu.au",
    logo_letter: "U",
    hero_color: "#0057A8",
    courses: [
      course("Master of Computing", "postgraduate", "IT", 24, 32800, 6.5, 4.5, true),
      course("Bachelor of Engineering (Honours)", "undergraduate", "Engineering", 48, 36000, 6.5, 3, true),
      course("Master of Education", "postgraduate", "Education", 24, 28200, 6.5, 4.5, true),
    ],
  },
  {
    id: "australian-catholic-university",
    name: "Australian Catholic University",
    short_name: "ACU",
    city: "Sydney",
    state: "NSW",
    qs_ranking_2025: 901,
    is_group_of_eight: false,
    cricos_code: "00004G",
    website: "https://www.acu.edu.au",
    logo_letter: "A",
    hero_color: "#C41230",
    courses: [
      course("Bachelor of Nursing", "undergraduate", "Health", 36, 33120, 7, 3, true),
      course("Master of Teaching (Primary)", "postgraduate", "Education", 24, 28400, 7, 4.5, true),
      course("Master of Social Work", "postgraduate", "Social Work", 24, 29760, 7, 4.5, true),
    ],
  },
  {
    id: "university-of-new-england",
    name: "University of New England",
    short_name: "UNE",
    city: "Armidale",
    state: "NSW",
    qs_ranking_2025: 1001,
    is_group_of_eight: false,
    cricos_code: "00003G",
    website: "https://www.une.edu.au",
    logo_letter: "U",
    hero_color: "#005BAC",
    courses: [
      course("Master of Computer Science", "postgraduate", "IT", 24, 31360, 6.5, 4.5, true),
      course("Bachelor of Nursing", "undergraduate", "Health", 36, 31920, 7, 3, true),
      course("Master of Teaching", "postgraduate", "Education", 24, 28640, 7, 4.5, true),
    ],
  },
];
